#!/usr/bin/env python
# -*- coding: utf-8 -*-
import json
file1 = open('D:\\queryexample.txt', 'w+')
data = []
queries = ['купить телевизор', 'купить телефон']
for query in queries:
	k = dict([('zone', 'ru'), ('language', 'ru'), ('near', 'Москва'), ('query', query)])
	k1 = dict(['data', k])
	data.append(k1)
print >>file1, data.encode('utf-8')
